phases:
  install:
    commands:
      - echo Starting Package Restore at `date`
      - 'dotnet restore'
  build:
    commands:
      - echo Starting Build
      - 'dotnet build -c Release'
      - 'dotnet publish -c Release'
  post_build:
    commands:
      - 'zip OpenApiNetCore.zip OpenApiNetCore/bin/Release/netcoreapp1.0/publish/*'
artifacts:
  type: zip
  files:
    - OpenApiNetCore.zip
