version: 0.2
phases:
  build:
    commands:
      - 'dotnet restore'
      - 'dotnet publish -c Release'
      - 'mv CoreLambda/bin/Release/netcoreapp1.0/publish/CoreLambda.zip CoreLambda.zip'
      - 'aws lambda update-function-code --function-name CoreLambda  --zip-file fileb://CoreLambda.zip'