version: 0.2
phases:
  install:
    commands:
      - echo Starting Package Restore at `date`
      - 'dotnet restore'
  build:
    commands:
      - 'dotner build -c Release'
      - 'dotnet publish -c Release'
      - 'zip OpenApiNetCore.zip OpenApiNetCore/bin/Release/netcoreapp1.0/publish/*'
  artifacts:
    files:
        - OpenApiNetCore.zip
    