phases:
  install:
    commands:
      - "dotnet restore"
  build:
    commands:
      - "dotnet build -c Release"
      - "dotnet publish -c Release"
  post_build: 
    commands:
      - "zip OpenApiNetCore.zip OpenApiNetCore/bin/Release/netcoreapp1.0/publish/*"