version: 0.2
phases:
  build:
    commands:
      - 'dotnet restore'
      - 'dotnet publish -c Release'
      - 'zip CoreLambda.zip CoreLambda/bin/Release/netcoreapp1.0/publish/*'
      - 'aws lambda update-function-code --function-name CoreLambda  --zip-file fileb://CoreLambda.zip'