AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Resources:
  OpenAPIApplicantApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: OpenApiNetCore::OpenApiNetCore.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore1.0
      MemorySize: 256
      Timeout: 30
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /v1/{proxy+}
            Method: ANY
