AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ProjectId:
    Type: String
    Description: OpenAPI Spike

Resources:
  OpenAPI.Applicant:
    Type: AWS::Serverless::Function
    Properties:
      Handler: OpenApiNetCore::OpenApiNetCore.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore1.0
      MemorySize: 256
      Timeout: 30
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
